name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Specify the .NET version you're using

    - name: Restore dependencies
      run: dotnet restore mahldcat.core.libraries.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore mahldcat.core.libraries.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal mahldcat.core.libraries.sln
